# Generated by Django 4.2.5 on 2023-09-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0003_alter_user_id_sensorreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='type',
            field=models.CharField(choices=[('temp', 'temperature'), ('humidity', 'humidity'), ('moisture', 'soil_moisture')], default='temp', max_length=100),
        ),
    ]
